name: Build-validator

on:
  workflow_run:
    workflows: 
      - Setup-python
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout corpus repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          path: corpus
      - name: Checkout validator repository
        uses: actions/checkout@v4
        with:
          repository: E-ARK-Software/eark-validator
          path: validator
      - name: Configure virtual environment
        run: |
          virtualenv -p python3 venv
          source venv/bin/activate
      - name: Update pip and install required packages
        run: |
          pip install -U pip
          pip install .
      - name: Run validator
        run: ip-check
      