name: Validate testcases

on: [push]

permissions:
  contents: read

jobs:
  checkout:
    name: Checkout repositories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout corpus repository
        uses: actions/checkout@v4
        with:
          path: corpus
      - name: Checkout validator repository
        uses: actions/checkout@v4
        with:
          repository: E-ARK-Software/eark-validator
          path: validator
  build:
    name: Build validator
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Print files
      run: ls -R
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install validator/.
    - name: Check validator
      run: ip-check